model {
  file: "model.sdf"
}
name: "Nescafe_Memento_Latte_Caramel_8_08_oz_23_g_packets_64_oz_184_g"
description: "Nescafe Memento Latte, Caramel - 8 - 0.8 oz (23 g) packets [6.4 oz (184 g)]\nSpecialty coffee beverage. Good food, good life. Good Question: How can I get coffeehouse quality foam that lasts until the final sip? Good to Know: By using real nonfat milk infused with airy bubbles NesCafe Memento brings you the frothy, foamy goodness you love. Natural source of antioxidants. 269 mg of antioxidants per serving. Product of Mexico."
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "NESCafe"
}
annotations {
  key: "gtin"
  value: "00028000204181"
}
annotations {
  key: "mpn"
  value: "nes98563"
}
annotations {
  key: "sku"
  value: "9286103_20130524_169033"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Consumer Goods"
}
